apiVersion: v1
kind: Service
metadata:
  name: livraison-front-service
  labels:
    app: livraison-front
spec:
  selector:
    app: livraison-front
  ports:
    - port: 443       # Port HTTPS exposé par le service
      targetPort: 443 # Port du conteneur (NGINX)
  type: LoadBalancer
