apiVersion: v1
kind: Service
metadata:
  name: livraison-front-service
  labels:
    app: livraison-front
spec:
  selector:
    app: livraison-front
  ports:
    - port: 4200       # Port exposé par le service
      targetPort: 4200 # Port du conteneur (NGINX)
  type: LoadBalancer
