apiVersion: v1
kind: Service
metadata:
  name: livraison-front-service
  labels:
    app: livraison-front
spec:
  selector:
    app: livraison-front

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
